language: go

go:
- 1.15.x

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip
  
script: 
  - go test ./... -cover -v -gcflags=-l
  - gox -arch="amd64" -os="windows linux" -output=bin/{{.Dir}}_{{.OS}}_{{.Arch}}

deploy:
  provider: releases
  api_key:
    secure: nBGulCdSEA6F2XWdpwozWBskI/OrpRp7GOorYRb0rg4TmrzjNuyBGo8rxlS9smZsehEs6j+GCoDzzAswig5vZD/lTQtxept/x+UETJ+9mNsScZzo1cSBFdJf2MkHBqx+WKShtz3KtpPT/KzKK5Asy8LFA0GL6YktmkzGy/vm8aDCRoF9F1TNT9dc7ygCHUbMrE+Uo28tyC2PVtqQ0Qte09d6SRZCz9rnSHg0vVJc6adjPW9Fcwd+xBcE5RcO91n2zAYYKTlNhPzTLvmGczKeRkRKthwgS3tC7Vp4NF6jBsKQ8E/qpf28rxrKWr8jz6RhRNfG7l4amBafGD6r+uL4eS97jsceYfc1lvcStcCUyA4opyA79HoIm3xH0AJ1F5HUHOVPfEJnEHdCNYmyM0e/sw9dzUxsuzfBrZa4Gj4mxnlwudglc88oe+JJ/RkvpXfmQnDz0w1KGJKdwfb7aRUeMXpcn5AMCyPEzyCdi/1oMD3w3tPLb2H/lQ1GxBRDyOIijxcq2ALO/pralEEQqZHscqSc8bHJDYpf+hr8vB46324FiSHcjuR3KU7bypjS9y5DQvxJFfvJH55fm0fRjxmo2Yet47f4MRI5WCqG2ykjFbgpU4Yq+x7k/dcPAPVWjOwGPq0i9Tovs9Z+E895644pJI05xnO+sEhE34Cwl7jdVBc=
  file_glob: true
  file: bin/*
  on:
    repo: TiboStev/hugo-wrapper
    tags: true
  skip_cleanup: 'true'
